### ISSUE TITLE
Build failing under Gradle 4.8

### ISSUE THREAD

**Issue by neonailol** [JetBrains/kotlin-native-calculator-sample#8]
I have problems building this sample with Gradle 4.8 under Windows
Error says: 
```
* What went wrong:
Could not determine the dependencies of task ':common:classes'.
> Task with path 'compileJava' not found in project ':common'.
```

I have the same problems with other multiplatform kotlin projects when building them with gradle 4.8

**Comment by olonho** [comment]
Gradle 4.7 shall be used with this sample

**Comment by cretz** [comment]
What would have to be done to make it compatible with the current Gradle version?

**Comment by joelhandwell** [comment]
Gradle 4.9 is released. Will this be still failing with 4.9?

**Comment by fuzzyweapon** [comment]
I think this is because the multiplatform plugin removes the compileJava task at some point (I believe I saw this in the source code somewhere but I can't dive in to look at it now) and this happens for me in 4.7 only when I have a multiproject build as an included build in a composite and then the multiproject build is being built after wiring up the composite/top-level build task to execute a buildAll task which depends on all of the build tasks in the multiproject(and multiplatform) included build via the recursive task collection method of getTasksByName (this was the /only/ way I could actually get that downstream task to correctly collect all the tasks in this context).

Then I ran into this error.  I've seen it once before I got to this point when I tried to upgrade to 4.8 and 4.9.  Getting it to occur in those versions is much more straightforward as @neonailol case probably demonstrates.

I can confirm that I am able to build multiplatform+multiproject builds without running into this issue on 4.7 (except in the circumstances above).

**Comment by fuzzyweapon** [comment]
I think the trick to getting around this will probably be adding back in a pseudo-task /after/ the multi-platform plugin does it's magic, which is what I'm going to try.

**Comment by fuzzyweapon** [comment]
Well this did not work for a naive approach.  Now the multiplatform plugin is complaining that it can't add the compileJava task because it already exists.  I will need to dig deeper into the plugin code to work around it I think.  My guess is now this is preventing the plugin from initially applying the java plugin, so I will ned to make sure this task is created after evaluation.

**Comment by fuzzyweapon** [comment]
Okay, for those that need a workaround for now, try this:
```
subprojects {
    val subProject = this
    plugins.withType<KotlinPlatformCommonPlugin> {
        project(subproject.path) {
            afterEvaluate {
               tasks {
                    val compileJava: JavaCompile by creating { }
                    val compileTestJava: JavaCompile by creating { }
                }
            }
        }
    }
}
```

This worked for me in my 4.7 case scenario and should theoretically work for 4.8+

It's only a workaround.

**Comment by RdeWilde** [comment]
@fuzzyweapon I can't get it to work on Groovy syntax.

I use this code in my subprojects `build.gradle`:
```
apply plugin: 'kotlin-platform-common'

// ...

plugins.withType(KotlinPlatformCommonPlugin) {
    project(path) {
        afterEvaluate {
            task compileJava(type: JavaCompile) {

            }
            task compileTestJava(type: JavaCompile) {

            }
        }
    }
}
```

But when I try to build, it gives me this error:
`Could not get unknown property 'KotlinPlatformCommonPlugin' for project ':kmulti-bignumber-common' of type org.gradle.api.Project.`

I tried adding `.class` to it, wrapping it in `Class<Kot..>` but none worked so far.

Got a clue?

**Comment by RdeWilde** [comment]
This seems to work:
```
plugins.withType(org.jetbrains.kotlin.gradle.plugin.KotlinPlatformCommonPlugin) {
```

**Comment by SvyatoslavScherbina** [comment]
This sample is outdated. Please see e.g. https://github.com/Kotlin/kmm-basic-sample instead.
More Kotlin Multiplatform Mobile samples can be found here: https://kotlinlang.org/docs/kmm-samples.html.
